### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by jonalbr** [papamidas/esp32_co2sensorcompare#1]
Hi,
did you get any results yet? 
Sincerely Jonas

**Comment by papamidas** [comment]
Hi jonas240,
yes, the results are documented on my [Homepage](https://dm1cr.de/co2-sensor-comparison-scd30-mh-z19b-bme680-vz89te-sgp30).
Just drop me a line if you have questions.
papamidas

**Comment by papamidas** [comment]
> 
> 
> Hi,
> did you get any results yet?
> Sincerely Jonas
